fix CellBookmark typings
https://github.com/ProseMirror/prosemirror-tables/pull/160
The CellBookmark type added here was incorrect and the following error is fixed.

```
index.ts:25:43 - error TS2322: Type 'CellSelection' is not assignable to type 'Selection'.
  The types of 'getBookmark().map' are incompatible between these types.
    Type '(mapping: Mapping) => CellBookmark' is not assignable to type '(mapping: Mappable) => SelectionBookmark'.
      Types of parameters 'mapping' and 'mapping' are incompatible.
        Type 'Mappable' is missing the following properties from type 'Mapping': maps, from, to, slice, and 5 more.

1      let state = EditorState.create({ doc, selection: CellSelection.create(table, 0) });
```